#!/bin/bash
#
# cmpcpits - generate gnuplot code that plots two Cycles Per Instructions
# time series in the same graph to allow for visual comparison
#
# USAGE: cmpcpits file1 file2 | gnuplot > graph.png
# USAGE: cmpcpits file1 file2 | gnuplot | display -
#
# The script takes as arguments 2 files generated by the x64ipc.sh
# script, and subsequently plots them in the same graph for comparison. A
# complete usage pattern would be something like:
#
# x64ipc.sh -q /path/to/binary1 > file1
# x64ipc.sh -q /path/to/binary2 > file2
# cmpcpits file1 file2 | gnuplot > graph.png
#

set -e
#set -x

b1=$(basename $1)
b2=$(basename $2)

paste <(awk '{ print $2 }' $1) \
      <(awk '{ print $2 }' $2) > $(dirname $1)/$b1-$b2.dat

# Escape _ as gnuplot will think that what follows it, is a subscript
e1=${b1//_/\\_}
e2=${b2//_/\\_}

cat<<EOF
set terminal png enhanced size 1024,768

set xlabel "sample #"
set ylabel "% Cycles Per Instruction (logscale)"
set logscale y

plot '$b1-$b2.dat' using 1 with points pointtype 6 title '$e1', \
     '$b1-$b2.dat' using 2 with points pointtype 7 title '$e2'
EOF
