#!/bin/bash

################################################################################
#
# The script takes as argument 2 files generated by the x64l2{dc,ic}misses.sh
# scripts, and 
#
################################################################################


set -e
#set -x

paste <(awk '{ print $4 }' $1) \
      <(awk '{ print $4 }' $2) > $1-$2.dat

e1=${1//_/\\_}
e2=${2//_/\\_}

cat<<EOF
set terminal png enhanced size 1024,768

set xlabel "time (0.1s)"
set ylabel "% Cache Misses (logscale)"
set logscale y

plot '$1-$2.dat' using 1 with points pointtype 6 title '$e1', \
     '$1-$2.dat' using 2 with points pointtype 7 title '$e2'
EOF
